

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Provider from "@/components/Provider/Provider";
import { Children } from "react";
import Provider from "@/components/Provider/Provider";
import Footer from "../components/Footer/page";
import WishlistContextProvider from "@/components/Context/WishlistContext";
import CartContextProvider from "@/components/Context/CartContext";

// import { Toaster } from "react-hot-toast";
// import CartContextProvider from "@/components/Context/CartContext";
// import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShopMart ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body 
       className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
   <Provider>
{/* <CartContextProvider > */}
    <WishlistContextProvider>
    {children}
    <Footer />
    </WishlistContextProvider >
    {/* </CartContextProvider > */}
   </Provider>
      </body>
    </html>
  );

}
